### ISSUE TITLE
Have a demo?

### ISSUE THREAD

**Issue by wq13718048209** [archriss/react-native-image-gallery#12]
This component of yours is very good. Can you write a reference for the demo? Many places will not use me as a friend from China. Thank you, Mr. Writer

**Comment by Exilz** [comment]
The code really isn't more complicated than the small snippet in the README.
Are you talking about a demo that you can try to "feel" the gallery ? If so, you can try this example live in **Archriss' showcase app** on [Android](https://play.google.com/store/apps/details?id=fr.archriss.demo.app) and [iOS](https://itunes.apple.com/lu/app/archriss-presentation-mobile/id1180954376?mt=8).

**Comment by Exilz** [comment]
@wq13718048209 A Demo has been added to this project. I hope this makes it easier for you.
