### ISSUE TITLE
How to prevent the image from resetting to the initial state when gesture released.

### ISSUE THREAD

**Issue by decodez** [archriss/react-native-image-gallery#16]
Hi, I am new to react-native and wondering how to make the image to stay zoomed in when gesture release. Like in the showcase app I want to zoom in and see the zoomed image after i remove finger instead of it resetting to the initial state

**Comment by Exilz** [comment]
Hi, the resetting is triggered automatically if your image's resolution isn't high enough.

To put it another way, the zoom won't stay after you release your touch if you're zooming at a ratio > 1.

**Comment by decodez** [comment]
Hey, @Exilz , Thanks for the prompt response that really helps. Much appreciated

**Comment by Exilz** [comment]
👍

**Comment by bigo104** [comment]
Why would image resolution stop zooming?

**Comment by Lump01** [comment]
### I solved double tap zooming and pinch zooming not staying by implementing the following minor code changes in TransformableImage/index.js and ViewTransformer/index.js:

"react-native-image-gallery": "2.1.5"

**TransformableImage/index.js**
```
let maxScale = 5;                            // change to whatever you want the max zoom in state to be
let contentAspectRatio;
let width, height; // imageDimensions

if (imageDimensions) {
    width = imageDimensions.width;
    height = imageDimensions.height;
}

if (width && height) {
    contentAspectRatio = width / height;
    // if (viewWidth && viewHeight) {         // code preventing zoom from staying based on image resolution
    //     maxScale = Math.max(width / viewWidth, height / viewHeight); 
    //     maxScale = Math.max(1, maxScale);
    // }
}
```

**ViewTransformer/index.js**
```
onResponderRelease (evt, gestureState) {
    let handled = this.props.onTransformGestureReleased && this.props.onTransformGestureReleased({
        scale: this.state.scale,
        translateX: this.state.translateX,
        translateY: this.state.translateY
    });
    // if (handled) {
    //     return;
    // }

    if (gestureState.doubleTapUp) {
```

My full patch file for the project is attached and includes a lot of minor changes like
- adding maxScale prop to <Gallery /> component
- removing all warnings regarding RN Version 0.70.0 and up
- allowing double tap and pinch zooming regardless of image resolution

[react-native-image-gallery+2.1.5.patch](https://github.com/meliorence/react-native-image-gallery/files/13368991/react-native-image-gallery%2B2.1.5.patch)
