### ISSUE TITLE
Broken doc link

### ISSUE THREAD

**Issue by msageryd** [archriss/react-native-image-gallery#17]
Thank you so much for taking care of this awesome seemingly abandoned library!

ldn0x7dc did an awesome work with his original library. I hope he is well and just abandoned his work due to priorities.

There is a minor link bug in the doc: The link to l`dn0x7dc/react-native-gallery` actually points to `ldn0x7dc/react-native-image-gallery` which does not exist.

**Comment by Exilz** [comment]
I updated it, thanks !
