### ISSUE TITLE
Where to display ActivityIndicator before the image has been loaded?

### ISSUE THREAD

**Issue by syedabdulbaqi** [archriss/react-native-image-gallery#18]
Where to display ActivityIndicator before the image has been loaded? Any prop or method to do this?

**Comment by Exilz** [comment]
You can use the `imageComponent` prop and render an image component that handles displaying a loader.
You can also do someting like this if you don't want to use a specific component :

```javascript
    renderImage (imageProps, dimensions) {
        const { width, height } = dimensions || {};
        // Display the loader until the dimensions are available, which means the image
        // has been loaded
        return width && height ? (
            <Image {...imageProps} />
        ) : (
            <ActivityIndicator />
        );
    }

...

            <Gallery
              imageComponent={this.renderImage}
              images={this._getImagesUrls(images)} />
```

You'll proably need a container around your ActivityIndicator, though.

**Comment by syedabdulbaqi** [comment]
imageComponent is not getting fired.


`          <Gallery
            initialPage={0}
            //renderPage={(pageData, pageId, layout) => { console.log('pagedata---->'); console.log(pageId); }}
            scrollEnabled={true}
            style={{flex: 1, backgroundColor: 'black'}}
            imageComponent={this.renderImage}
            images={this.state.data}
            errorComponent={this.renderError}
            onPageSelected={(page) => { this.pageSelected(page); }}
          />`

`    renderImage (imageProps, dimensions) {
        console.log('inside render image...');
        const { width, height } = dimensions || {};`

There is no log message ('inside render image...') in the console. Am I missing something?

**Comment by Exilz** [comment]
Looks good to me. What version of the module are you using

**Comment by syedabdulbaqi** [comment]
"react": "16.0.0-alpha.12",
    "react-native": "^0.46.1",
    "react-native-elements": "^0.16.0",
    "react-native-google-analytics-bridge": "^5.3.1",
    "react-native-image-gallery": "^1.1.0",
    "react-native-multi-slider": "^0.3.6",
    "react-native-vector-icons": "^4.3.0",
    "react-navigation": "^1.0.0-beta.11"

**Comment by Exilz** [comment]
`imageComponent` is new. You need to upgrade to `2.0.0` 😄

**Comment by syedabdulbaqi** [comment]
@Exilz It is working now. Thanks :+1:

**Comment by Exilz** [comment]
Great 👍

**Comment by guptayush** [comment]
The Gallery hangs after sliding 2-3 times if using imageComponent as describes above

**Comment by JanithaR** [comment]
```
getCustomImageComponent = (imageProps, dimensions) => {
        return <View>
            <ActivityIndicator style={{
                position: 'absolute',
                left: 0,
                top: 0,
                right: 0,
                bottom: 0,
                justifyContent: 'center',
                alignItems: 'center'
            }} />
            <Image {...imageProps}
                onLoadStart={() => { console.log('on load start'); }}
                onLoad={() => { console.log('on load'); }}
                onLoadEnd={() => { console.log('on load end'); }} />
        </View>;
    };
```

**Comment by gpalsingh** [comment]
```js
renderImage (imageProps, dimensions) {
    // Hide the loader after image loads
    return (<View>
        { !imageProps.imageLoaded &&
            <ActivityIndicator color='white' style={styles.activityIndicatorStyle}/>
        }
        <Image {...imageProps} />
    </View>);
}

/* Outside of class */
const styles = StyleSheet.create({
    activityIndicatorStyle:{
        position: 'absolute',
        alignItems: 'center',
        justifyContent: 'center',
        top: '10%',
        bottom: '10%',
        left: 0,
        right: 0,
    },
});
```

A little late, but a slightly modified version that worked for me using combination of solutions from @Exilz and @JanithaR 😄
