### ISSUE TITLE
Support onLongPress

### ISSUE THREAD

**Issue by davidpaulsson** [archriss/react-native-image-gallery#2]
Would it be possible to add support for `onLongPress`? I would like to add the possibility to open an action sheet with additional actions for images.

**Comment by Exilz** [comment]
Sure, I'll look into it next week along with the issue with
shallow-compare.
Le ven. 12 mai 2017 à 13:20, David Paulsson <notifications@github.com> a
écrit :

**Comment by davidpaulsson** [comment]
What a champ 👏

**Comment by Exilz** [comment]
@davidpaulsson I added in in the latest release !
