### ISSUE TITLE
onPageScroll event

### ISSUE THREAD

**Issue by gabrirulli** [archriss/react-native-image-gallery#22]
I need to check if half of the next image is shown.
I tried with something like that:
```
<Gallery
      style={{flex: 1}}
      images={this.state.images}
      pageMargin={20}
      onPageScroll={(event) => this.scrollEvent(event)}
   />
scrollEvent(event) {
    console.log(event);
    if (event["fraction"] == 0.5) {
      console.log("half page");
    }
}
```

It didn't work. What can i do?

**Comment by vbuch** [comment]
Events are throttled if I remember correctly. So you would need to go deeper in the code and handle them before throttling. Also I doubt you would ever get exactly 0.5. Rather something in the range 0.4:0.6
