### ISSUE TITLE
Adding new image to the beginning of images array causes rerendering & problem

### ISSUE THREAD

**Issue by batuypn** [archriss/react-native-image-gallery#23]
I have a large list of images, so that i am starting my Gallery images array with the size of 3.
When i slide left the initial image (my init is middle), i am adding new image to end of the array, there is no problem.
``
this.setState({images: [...this.state.images, newImage]})
``
But, when i slide right, adding new image to the beginning of array, results in rerendering the current image and selected page became my new image (index 0). Therefore, i cannot slide right again.
``
 this.setState({images: [newImage, ...this.state.images]})
``

**Comment by vbuch** [comment]
Rendering and listing is based on indexes in the array so pushing stuff on the left will surely mess things up as indexes will change.

**Comment by batuypn** [comment]
thank you for your answer but can you suggest any solution for me? @vbuch

**Comment by vbuch** [comment]
No idea actually. I can't even imagine why would you need to push photos to
the start of the gallery. I would say that after you have pushed a photo
you could scrollToPage +1 but knowing how it works I can't imagine this
happening smoothly.

На пт, 6.10.2017 г., 19:01 Batuhan Yapanoglu <notifications@github.com>
написа:

**Comment by compojoom** [comment]
@vbuch 

> I can't even imagine why would you need to push photos to the start of the gallery

Pretty simple. If you are dealing with dynamic images. You open an image and scrolling to the left will show you images that were made before the current one and scrolling right would show you newer images. If you are dealing with images that are stored on a server and you don't know in advance how your images array should look - you need to be able to push to both sides of the array.
