### ISSUE TITLE
Gallery now showing up on iOS

### ISSUE THREAD

**Issue by jbouaziz** [archriss/react-native-image-gallery#25]
Hello, I've implemented your gallery which works great on Android but doesn't shows up as a black screen on iOS.
![screen shot 2017-10-05 at 10 12 48](https://user-images.githubusercontent.com/3008860/31217034-ef61688a-a9b5-11e7-9e9c-c5f9b018e7b9.png)

The code I'm using:
``` jsx
import React, {Component} from 'react'
import {Platform, View} from 'react-native'
import {Container, Content, Header, Left, Right, Title, Icon, Button, Text} from 'native-base'
import Gallery from 'react-native-image-gallery';

export default class GalleryScreen extends Component {
    static navigationOptions = {
        header: null,
    }
    
    render() {
        const { goBack } = this.props.navigation;
        const { params } = this.props.navigation.state;
        let data = params.images.map(item => {
            return {source: {uri: item}}
        })
        let initialPage = params.initialPage ? params.initialPage : 0
        return (
            <Container>
                <Header
                    style={{backgroundColor: 'transparent', position: 'absolute', top: 0, left:0, right: 0, zIndex: 5}}
                    androidStatusBarColor={'black'}
                    noShadow={true}
                    >
                    <Left>
                        <Button transparent onPress={() => goBack()}>
                            <Icon name="md-close"/>
                        </Button>
                    </Left>
                    <Right>
                        <Button transparent>
                            <Icon android="md-share" ios="ios-share-outline"/>
                        </Button>
                    </Right>
                </Header>
                <View style={{flex: 1}}>
                    <Gallery
                        initialPage={initialPage}
                        style={{ flex: 1, backgroundColor: 'black' }}
                        images={data}
                        />
                </View>
            </Container>
        )
    }
}
```

The `images` prop is an array of asset library items. I also tried using remote images but got the same result.

Is there something wrong with my implementation?

**Comment by sayhei** [comment]
me too ......

**Comment by Exilz** [comment]
@sayhei thanks for your *great* input on this issue.

@jbouaziz the path on your screenshot with your local image seems a bit weird. Regarding remote images, are you sure you've allowed the domains of your images in your application transport settings ? This is a common issue with images on iOS.

This issue reminds me of #7

**Comment by jbouaziz** [comment]
It's a local asset library item, fetched using the `CameraRoll` methods. I've also tried using a remote image with an `https` link (_http://i.imgur.com/XP2BE7q.jpg_) but it didn't work either.

I also tried using static data like the one in the README:
```jsx
<Gallery
    initialPage={initialPage}
    style={{ flex: 1, backgroundColor: 'black' }}
    images={[
          { source: { uri: 'https://i.imgur.com/XP2BE7q.jpg' } },
          { source: { uri: 'https://i.imgur.com/5nltiUd.jpg' } },
          { source: { uri: 'https://i.imgur.com/6vOahbP.jpg' } },
          { source: { uri: 'https://i.imgur.com/kj5VXtG.jpg' } }
        ]}
    />
```

@Exilz thanks for looking into it!

**Comment by jbouaziz** [comment]
You only need to declare non-secure websites to your `Info.plist` ATS key: servers that don't have the required tls version or simply using https. That I'm sure of.

I tried using the `dimensions` key too but since I have an url and not an `Image object I'm getting a warning from the library.

I also tried to debug if the image size was correctly found using the `Image.getSize` method in `TransformableImage/index.js` and it worked this far.

**Comment by Exilz** [comment]
Well, I'm out of ideas right now. What's your version of react and react-native ?

**Comment by jbouaziz** [comment]
Yeah me too, that really puzzles me and I'm thinking that it might something related to flex or else.
```
"react": "16.0.0-alpha.12",
"react-native": "^0.48.3",
```

**Comment by jbouaziz** [comment]
It was a layout issue which was fixed by using a custom header view for iOS inside the `Gallery` and by using the default `Content` native base component as a wrapper.

For those who end up having the same issue:
```jsx
<Container>
    { this.renderAndroidNavBar() }

    <Content scrollEnabled={false}>
        <Gallery
            initialPage={initialPage}
            style={{ flex: 1, backgroundColor: 'black' }}
            onPageSelected={this.onPageSelected}
            images={images}
        />

        { this.renderiOSNavBar() }
    </Content>
</Container>
```

**Comment by mairi17** [comment]
I found the same blank screen issue as @jbouaziz 
My project uses [react-navigation](https://github.com/react-community/react-navigation)
To demonstrate the problem, I made an example project based on react-navigation's ReduxExample project combined with react-navigation-image-gallery's DemoGallery. It's at [image_gallery](https://github.com/mairi17/react-navigation/tree/image_gallery) - the DemoGallery should show on the profile screen, but it only works on Android, and the images are blank on iOS.

**Comment by mairi17** [comment]
For those who end up having the same issue and don't use Native Base, nesting the Gallery in a disabled ScrollView worked for me:
``` 
<ScrollView style={styles.ImageGallery} scrollEnabled={false}>
   <Gallery />
</ScrollView>

**Comment by jeffzing** [comment]
@mairi17 you are so nice
`            <ScrollView scrollEnabled={false}>
                <Gallery
                    initialPage={index}
                    style={{ flex: 1, backgroundColor: 'black' }}
                    images = {imageUrls}
                    onPageSelected = {this._onPageSelected}
                    imageComponent = {BigImage._renderImageComponent}
                    onSingleTapConfirmed = {this._closeBox}
                    errorComponent = {BigImage._loadErro}
                    // imageLoadingActivityIndicator = {BigImage._loadingIndicator}
                />
            </ScrollView>`
worked for my code, but why?

**Comment by jeffzing** [comment]
@mairi17 and this issue only on iphone7 iOS 10,all my other iPhone does not have it
