### ISSUE TITLE
initalpage not working --- always displaying  index 0 of the images list

### ISSUE THREAD

**Issue by danielyoon2013** [archriss/react-native-image-gallery#27]
I have been struggling to display the selected image from the list of images on my app.
"this.state.currentPhotoIndex" is the index of the selected image and my render function is following :

                <Gallery
                  images={this.state.allPhotos}
                  initialPage={this.state.currentPhotoIndex}
                  onPageSelected={(index) => this.onPageChange(index)}
                />

The problem is that inside nodemodules -> libraries -> viewPager, when I console log the following part,

 componentDidUpdate (prevProps) {
        if (!this.initialPageSettled) {
            this.initialPageSettled = true;
            ******console.log("THIS IS FROM DEEP INSIDE THE MODEL : ", this.props.initialPage);*******
            this.scrollToPage(this.props.initialPage, true);
        } else if (this.layoutChanged) {
            this.layoutChanged = false;
            if (typeof this.currentPage === 'number') {
                this.scrollToPage(this.currentPage, true);
            }
        } else if (this.currentPage + 1 >= this.props.images.length &&
            this.props.images.length !== prevProps.images.length) {
            this.scrollToPage(this.props.images.length, true);
        }
    } 

it always shows "THIS IS FROM DEEP INSIDE THE MODEL :  0".

I am not quite sure this is because i am using redux and have been spending too much time on this. It would be helpful if there is someone who has finished struggling with this issue.

**Comment by jbouaziz** [comment]
Have you tried using the latest version? It fixed it for me.

**Comment by philipheinser** [comment]
@danielyoon2013 Works in our app. What version do you use?

**Comment by danielyoon2013** [comment]
Upgrading to latest version now works perfectly in iOS version, though there are some more issues to handle in android. Thank you for your support.
