### ISSUE TITLE
doubleTap not working

### ISSUE THREAD

**Issue by davidpaulsson** [archriss/react-native-image-gallery#3]
If I use this as a drop-in replacement for ldn0x7dc's lib (the only thing I'm changing is adding the `{ source: { uri } }` structure of the data source, everything seems to work, _but_ double tap to zoom stops working.

**Comment by Exilz** [comment]
1.1.0 should fix this

**Comment by davidpaulsson** [comment]
I'll try it out! Thanks! 👊

**Comment by yozman** [comment]
@Exilz
doubleTap still not work

**Comment by Lump01** [comment]
### I solved double tap zooming and pinch zooming not staying by implementing the following minor code changes in TransformableImage/index.js and ViewTransformer/index.js:

"react-native-image-gallery": "2.1.5"

**TransformableImage/index.js**
```
let maxScale = 5;                            // change to whatever you want the max zoom in state to be
let contentAspectRatio;
let width, height; // imageDimensions

if (imageDimensions) {
    width = imageDimensions.width;
    height = imageDimensions.height;
}

if (width && height) {
    contentAspectRatio = width / height;
    // if (viewWidth && viewHeight) {         // code preventing zoom from staying based on image resolution
    //     maxScale = Math.max(width / viewWidth, height / viewHeight); 
    //     maxScale = Math.max(1, maxScale);
    // }
}
```

**ViewTransformer/index.js**
```
onResponderRelease (evt, gestureState) {
    let handled = this.props.onTransformGestureReleased && this.props.onTransformGestureReleased({
        scale: this.state.scale,
        translateX: this.state.translateX,
        translateY: this.state.translateY
    });
    // if (handled) {
    //     return;
    // }

    if (gestureState.doubleTapUp) {
```

My full patch file for the project is attached and includes a lot of minor changes like
- adding maxScale prop to <Gallery /> component
- removing all warnings regarding RN Version 0.70.0 and up
- allowing double tap and pinch zooming regardless of image resolution

[react-native-image-gallery+2.1.5.patch](https://github.com/meliorence/react-native-image-gallery/files/13368991/react-native-image-gallery%2B2.1.5.patch)
