### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by ironmanromeo** [archriss/react-native-image-gallery#30]
Sometimes the picture did not appear. I looked into the code and discovered that there is an undocumented props: "loader". Passing a view the problem has resolved. I suggest inserting a default loading view and above all to add it to the documentation.

**Comment by prosperi** [comment]
I have the same issue, it does not show images on IOS. How did you solve it exactly ?

**Comment by ironmanromeo** [comment]
<Gallery
   initialPage={index}
                            style={{flex: 1}}
                            loader={<Text>loader</Text>}
                            onPageSelected={(pageSelected) => this.setState({pageSelected})}
                            images={user.media.map(m => ({source: {uri: m.uri}} ))}
                        />
