### ISSUE TITLE
Not rendering more than 10 items?

### ISSUE THREAD

**Issue by InYourDreamz** [archriss/react-native-image-gallery#31]
Ok, this might be a little question. Is there a reason why it could only render 10 images from an array or 24? And if this was intended, how do I render the rest of the array?

**Comment by chrusart** [comment]
Could you provide some reproduction steps?
When it happen, on initial page > 10?
It can be the same I had with FlatLists component.

**Comment by InYourDreamz** [comment]
Nothing special actually, I'm taking from the example and using this array source.

[array.txt](https://github.com/archriss/react-native-image-gallery/files/1406162/array.txt)

and the code is
```
            <Gallery
                imageComponent={this.renderImage}
                images={this.state.images}
                initialPage={0}
                onPageSelected={this.onChangeImage}
                errorComponent={this.renderGalleryError}
              />
```

Maybe the behaviour is built in such a way that it will only load 10 and you have to load the next 10?

**Comment by chrusart** [comment]
Nooo, if you have all images in state.images this should work.

**Comment by chrusart** [comment]
btw. @Exilz I was busy and couldn't go back to you about 2.0 version, but I had still some issues and I am still using my branch. Will try look at current version soon.

**Comment by InYourDreamz** [comment]
@chrusart oh, it is in a state. 
I attached the txt file here in case you'd like to have a look at it.

**Comment by chrusart** [comment]
Yeah, I saw it, I don't think you made errors in a file.

**Comment by Exilz** [comment]
Is it still a problem with the latest version of the plugin ?

**Comment by alainib** [comment]
i have an issue like this. if images contain for example 200 elements, if i put initalPage  = 30 it don't work ( don't display the good image and cannot go left and right)

**Comment by rskull** [comment]
same issue

**Comment by a-c-sreedhar-reddy** [comment]
You may have to  pass `initialNumToRender` to the flatlist prop whose default value is 10.
