### ISSUE TITLE
issue compiling Gallery: _react3.default.PropTypes.bool

### ISSUE THREAD

**Issue by reybluk** [archriss/react-native-image-gallery#32]
### Version
react-native-image-gallery@1.1.0

###dev Os: MAcOsX

### Target Platforms
iOS | Android

### Target OS version
iOS 10| android 5.1.1 or major...

### React info:
react-native version: `0.49.3`
react version: `16.0.0-beta.5`
react-native-cli: `2.0.1`
node version: `7.8.0`
npm version: `5.5.1`

### To install I tried 2 way.
This the passes of the first
1. sudo npm install --save react-native-gallery-image

and this the second way:
1.  sudo npm install npm@latest -g
2.  sudo npm install --save react-native-gallery-image
3.  sudo react-native link react-native-image-gallery

I don't have warning about gallery...

### Expected behavior
install must go fine and use it in react project

### Actual behavior
when I compile on my nexus 4 (Android 5.1.1) it throw exception:
_react3.default.PropTypes.bool as screencapture
![screenshot_2017-10-24-23-43-56](https://user-images.githubusercontent.com/23139315/31969667-bd439ce6-b915-11e7-8e80-ad65cf45ac71.png)

Have you any solutions?

Thank you for all anyway

**Comment by georgegoncalo** [comment]
Hey.

PropTypes isnt an object of react anymore (0.49).

Must be changed to `import PropTypes from 'prop-types'`

;)

**Comment by bd-arc** [comment]
Hi @reybluk,

You need to either:
- use a more recent version of the plugin (the fix has been published in [version `2.1.2`](https://github.com/archriss/react-native-image-gallery/releases/tag/v2.1.2))
- downgrade to RN 0.48 (in which it was still possible to import `PropTypes` from `React`, as @georgegoncalo stated)

**Comment by reybluk** [comment]
I couldn't do downgrade. I have a module that needed 0.49. For me is ok install new version... but I don'tknow how to do it without standard install... Could you help me? only copy the gallery.js and substitute previous one? or I copy all `src` folder in `/node_modules/react-native-image-gallery/library/`folder?

**Comment by bd-arc** [comment]
@reybluk You should never modify the files that are located in the `nodes_modules` folder unless you have a very good reason to do so (usually in order to test an unpublished fix); `npm` is there precisely to handle that for you.

Updating the plugin version is as simple as modifying your `package.json` file to the following:
```
"react-native-image-gallery": "2.1.3"
```
and then running:
```
npm install
```

Make sure to read [the release notes of version `2.0.0`](https://github.com/archriss/react-native-image-gallery/releases/tag/v2.0.0) since a small breaking change was introduced.
