### ISSUE TITLE
Add a method to scroll to a specific slide

### ISSUE THREAD

**Issue by rubengarciam** [archriss/react-native-image-gallery#37]
Firstly, thanks for creating your own repo and pushing @ldn0x7dc's work! 👏

Could it be possible to render an image dynamically (from the background) once the Gallery is in the foreground? 

Example: there's an overlay with a slider that mirrors the number of pages from the gallery. When the slider is dragged, call a function to render such page # in the Gallery.

This could be something in the lines of: _this.refs['gallery'].setPage(pageNumber)_ 

when the component has been created _<Gallery ref="gallery" ..._

**Comment by Exilz** [comment]
Hi, I'm not sure to understand what you'd want.
Is it just a method to scroll to a specific slide ?

**Comment by rubengarciam** [comment]
> Is it just a method to scroll to a specific slide ?

That's correct @Exilz

**Comment by slorber** [comment]
@rubengarciam it seems you can trigger slide by calling vewpager methods

this.gallery.getViewPagerInstance().scrollToPage(page);

**Comment by slorber** [comment]
what would be more interesting would probably be to make the gallery controlled, ie the parent component can pass a "page" props and the gallery would automatically scroll to the appropriate page instead of holding it as internal state

**Comment by rubengarciam** [comment]
Thanks @slorber Using

`this.refs[REF].getViewPagerInstance().scrollToPage(page)`

worked great :)

**Comment by akhilesh-leap-club** [comment]
Thanks @slorber Using
```
<Gallery
                          ref={galleryRef}
                          // remaining props...
                      />
```
const galleryRef = useRef(null);
galleryRef.current.getViewPagerInstance().scrollToPage(page)

worked like a charm :)
