### ISSUE TITLE
Image zooming bounces back once touch is released

### ISSUE THREAD

**Issue by alphasp** [archriss/react-native-image-gallery#4]
Once I release touch, the image zooming bounces back to original position and size. Any idea what the problem might be? 
I tried `setting onTransformGestureReleased={() => true}` from  https://github.com/ldn0x7dc/react-native-transformable-image/issues/13#issuecomment-268262048 but image still bounce back to original position and size.

**Comment by Exilz** [comment]
This seems to be related to #3,
I think I managed to resolve this. I'll be releasing a fix shortly

**Comment by yozman** [comment]
@Exilz
hey, still not work

**Comment by howg0924** [comment]
Same problem here. Using react-native-image-gallery version 2.1.5 and RN 0.51 and Android platform.

**Comment by Lump01** [comment]
### I solved double tap zooming and pinch zooming not staying by implementing the following minor code changes in TransformableImage/index.js and ViewTransformer/index.js:

"react-native-image-gallery": "2.1.5"

**TransformableImage/index.js**
```
let maxScale = 5;                            // change to whatever you want the max zoom in state to be
let contentAspectRatio;
let width, height; // imageDimensions

if (imageDimensions) {
    width = imageDimensions.width;
    height = imageDimensions.height;
}

if (width && height) {
    contentAspectRatio = width / height;
    // if (viewWidth && viewHeight) {         // code preventing zoom from staying based on image resolution
    //     maxScale = Math.max(width / viewWidth, height / viewHeight); 
    //     maxScale = Math.max(1, maxScale);
    // }
}
```

**ViewTransformer/index.js**
```
onResponderRelease (evt, gestureState) {
    let handled = this.props.onTransformGestureReleased && this.props.onTransformGestureReleased({
        scale: this.state.scale,
        translateX: this.state.translateX,
        translateY: this.state.translateY
    });
    // if (handled) {
    //     return;
    // }

    if (gestureState.doubleTapUp) {
```
