### ISSUE TITLE
Click Handler

### ISSUE THREAD

**Issue by yasinugrl** [archriss/react-native-image-gallery#41]
Can this library provide click handler for go next image? Or is there any way to make this?

**Comment by Exilz** [comment]
Hi, are you looking for a method to slide to a specific slide ? I'm not sure I understand what you mean by "handler".

**Comment by slorber** [comment]
Hi,

I need something similar: ability to press next/previous arrows

**Comment by Exilz** [comment]
I'm gonna close this issue as it is a duplicate of #37
