### ISSUE TITLE
Maybe also bake in a copy of react-native-scroller

### ISSUE THREAD

**Issue by msageryd** [archriss/react-native-image-gallery#43]
I guess that you left the scroller lib out on purpose when you copied the other components from the original repo as there will probably not be any need for new features or bug fixes. 

@ldn0x7dc hasn't been heard from in a very long time. What will happen if his repos are removed? Would it be safer to have a bundled copy in this lib? I just forked scroller myself, just in case. I also noticed that there where only one other fork.

**Comment by Exilz** [comment]
You're right, better safe than sorry.
I forked the repo too, and I'll try to bake it in in the next release.

If someone wants to do it, please make sure to follow the code style from the supplied `.eslintrc` file.

**Comment by msageryd** [comment]
On the code style topic. Have you considered using Prettier to ensure consistent formatting?

**Comment by Exilz** [comment]
When writing code from scratch I usually just follow eslint to make sure it's consistant.
Since I pretty much changed the whole original codebase here, maybe I should have used prettier. It might not be perfectly consistant everywhere.

**Comment by msageryd** [comment]
I have now bundled react-native-scroller and react-native-gesture-responder into react-native-image-gallery. I'm having trouble creating a PR because of the PR you already got on the Rect-bug. 

I'll make a PR out ot the bundling when you (hopefully) have merged my last PR.

I should probably have used branches to sort this out, but I'm not very good with Git.

**Comment by Exilz** [comment]
Shipped in `2.1.5`, thanks.
