### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by scotbond** [archriss/react-native-image-gallery#5]
Hi,
On RTL mode, only the first image is shown, swiping left shows empty pages.
This happens due to wrong flexDirection (of ScrollView).
The normal solution would be something like:
`flexDirection: I18nManager.isRTL ? 'row-reverse' : 'row'`

I know it will require a change in `react-native-view-pager` as well (no github repo?) , but can you please work something out? it is really critical for us.
Thanks!

**Comment by scotbond** [comment]
[PR](react-native-view-pager) opened on `react-native-view-pager`. closing.

**Comment by Exilz** [comment]
Hey,
feel free to re open this issue if your PR never gets merged.
We'll work something out.
