### ISSUE TITLE
I test on my apple cell phone, I can't show the picture. I don't know why, please reply to me as soon as possible.

### ISSUE THREAD

**Issue by guoguoss** [archriss/react-native-image-gallery#59]
I test on my apple cell phone, I can't show the picture. I don't know why, please reply to me as soon as possible.

**Comment by msageryd** [comment]
You need to provide more information of what you're doing. A code example might help.

**Comment by Exilz** [comment]
On iOS, don't forget to add the domains of your remote images to the app transport security.

**Comment by guoguoss** [comment]
Add the domain of the remote image to application transport security what does this mean

**Comment by Exilz** [comment]
http://lmgtfy.com/?q=add+domains+to+app+transport+security

If this doesn't fix it for you, please re-open an issue **with your code** and a clear explanation of what you're doing.

**Comment by guoguoss** [comment]
Sorry but the link you replyed cann't show the entire image . Please show me the procedure by source code . 
My code is to download the pictures on the iphone, but failed to load.  The code is attached below. I'm expecting your advise. Thank you. 
`const images=[
    { caption: 'Caption 4', source: require('../../../img/page/secpress.png') },
    { caption: 'Caption 5', source: require('../../../img/page/secpress.png') },
    { caption: 'Caption 6', source: require('../../../img/page/secpress.png') },
    { caption: 'Caption 7', source: require('../../../img/page/secpress.png') },
    { caption: 'Caption 8', source: { uri: 'http://i.imgur.com/BN8RVGa.jpg' } },
    { caption: 'Caption 9', source: { uri: 'http://i.imgur.com/jXbhTbv.jpg' } },
    { caption: 'Caption 10', source: { uri: 'http://i.imgur.com/30s12Qj.jpg' } },
    { caption: 'Caption 11', source: { uri: 'http://i.imgur.com/4A1Q49y.jpg' } },
    { caption: 'Caption 12', source: { uri: 'http://i.imgur.com/JfVDTF9.jpg' } },
    { caption: 'Caption 13', source: { uri: 'http://i.imgur.com/Vv4bmwR.jpg' } }
]
export default class CeShiImage extends Component{
    constructor(props){
        super(props)
        this.state={
            page:0
        }
    }
    static navigationOptions = ({navigation, screenProps}) => ({

        header: null,
        gesturesEnabled:false,
    })
    render(){
        const list=this.props.navigation.state.params.data;
        const index=list.length
        return(<View style={{flex:1}}>
            <View style={[styles.titleView]}>
                <View style={comstyle.rightview}>
                    <View  style={styles.hua}>
                <Text style={styles.title}>{this.state.page+1}/{index}</Text>
                    </View>
                </View>
                <TouchableOpacity onPress={()=>{this.props.navigation.goBack()}}>
                <Image source={require('../../../img/page/arrow.png')} style={styles.arr}/>
                </TouchableOpacity>
            </View>
            <Gallery
                style={{flex:1}}
                images={images}
                // initialPage={0}
                onPageSelected={(page)=>{
                    this.setState({
                        page:page
                    })
                }}
            />
        </View>)
    }}`

**Comment by msageryd** [comment]
Hey, don't forget that the people working on this lib do it for free. You'd be better off in the open source community if you'd **"kindly ask for advice"** instead of **"expect advice"**.

Anyway.. You need to use **https** for your images or register your **unsecure** http domain in info.plist. Please Google "ios transport security" to solve this. It has nothing to do with react-native-image-gallery.

**Comment by Exilz** [comment]
Please [read the docs](https://github.com/archriss/react-native-image-gallery#remote-and-local-images). Part of your problem is obvious.
