### ISSUE TITLE
Image Gallery crashes after delete

### ISSUE THREAD

**Issue by mlecoq** [archriss/react-native-image-gallery#6]
I have added on each picture a delete button to remove pictures. 
Deletion is ok but when I have 1 picture left and I move it, I have an issue (evaluating getCurrentImageTransformer)

![img_1231](https://user-images.githubusercontent.com/3649784/26935087-563a8b7a-4c6b-11e7-8fcf-872702ea7dbb.PNG)

**Comment by krailler** [comment]
Same here.. any fix?

**Comment by Exilz** [comment]
Hi, it's probably a bug (well, a lack of feature) of a dependency (I guess`react-native-gesture-responder`).
I don't really have much time to investigate it for the moment.

**Comment by Exilz** [comment]
As I said on this issue #9 , we need to provide `react-native-transformable-image`, `react-native-view-pager` and `react-native-gesture-responder` directly in our codebase in order to be able to properly fix each of them independently.

This should be the priority right now.

**Comment by chrusart** [comment]
Not sure if it's a gesture responder bug or just maintaining their refs in Gallery

**Comment by Exilz** [comment]
@mlecoq @chrusart this should be fixed in the next version of the plugin, I'll publish a release candidate ASAP.

**Comment by Exilz** [comment]
@mlecoq could you check out `1.2.0-rc.3` on npm and tell me if it fixed it for you ?

**Comment by mlecoq** [comment]
I have tested 1.2.0-rc.4 and this problem is fixed. 

I have a new one unfortunately. When I close and reopen the gallery, first time works fine but then the screen is black (until I move it from vertical to horizontal). 
Displayed pictures are updated through redux. 

Looks strange, I will make more tests later.

Thanks !

**Comment by a-c-sreedhar-reddy** [comment]
Hi @mlecoq ! How did you fix this issue?

**Comment by mlecoq** [comment]
I don't remember 😁 and I have no more access to the code of this app
