### ISSUE TITLE
imageComponent does not work as expected

### ISSUE THREAD

**Issue by EduardJS** [archriss/react-native-image-gallery#60]
Hello! I'm just trying to use `FastImage` as image component by doing the following:

```javascript
<Gallery 
	imageComponent={FastImage}
	images={this.state.images} 
	style={{ flex: 1 }} 
/>
```

Problem is, I always get a blank screen, no errors, nothing. Also tried with `CachedImage`, same result. Even though, I'm using the component directly, somewhere else, and works just fine, so it's not related to the modules themselves.

Any advice ?

**Comment by msageryd** [comment]
I've tried FastImage with react-native-image-gallery. I don't recall having to do something special to get it working. But I do have a note in one of my documents telling me that I didn't get any noticeable performance gain with FastImage, hence I ended up not using it.

**Comment by EduardJS** [comment]
Well, if it's no help, then I'll just drop it. Thanks for the input

**Comment by msageryd** [comment]
Oh, I see not that you're setting FastImage as `imageComponent`. I haven't used this property, but I think you are supposed to supply a complete component with a working `render()` function. Just providing an empty class (FastImage) will not give the information needed to image-gallery for rendering the image.

**Comment by qalqi** [comment]
For reference 
```
const fastImageComponent = props => <FastImage {...props}></FastImage>;

   <Gallery
         imageComponent={fastImageComponent} />
```
