### ISSUE TITLE
Black screen with example

### ISSUE THREAD

**Issue by ayozemr** [archriss/react-native-image-gallery#7]
Hello!

Just testing this gallery with the example I get a black scene. I see some console.logs in debugger:
```
animate...equal rect, skip animation
performDoubleTapUp...pivot=197, 344.5
```

My code:
```
export default class ProposalImageGallery extends React.Component {
    static propTypes = {
    }
    static defaultProps = {
    }
    render() {
        return (
            <Gallery
                style={{flex: 1, backgroundColor: 'black'}}
                images={[
                    { source: { uri: 'http://p10.qhimg.com/t019e9cf51692f735be.jpg' } },
                    { source: { uri: 'http://ww2.sinaimg.cn/mw690/714a59a7tw1dxqkkg0cwlj.jpg' } },
                    { source: { uri: 'http://www.bz55.com/uploads/allimg/150122/139-150122145421.jpg' } },
                ]}
            />
        )
    }
}
```

We are using RN 0.45

Any advice @Exilz ?
Thanks for your time!

**Comment by Exilz** [comment]
Hi @ayozemr ,
do you have the latest version of the plugin ?

Have you tried with local images ? (don't forget the `dimensions` key !)

Are you testing on iOS ? Do you have ATS enabled without these domains by any chance ?

**Comment by ayozemr** [comment]
Hello!

Yes, seems that iOS and Android by default do not load insecure remote images, changing example images by secure ones worked :-)


Thanks!
