### ISSUE TITLE
Adding images dynamically

### ISSUE THREAD

**Issue by FabulouSebas** [archriss/react-native-image-gallery#79]
Hi!
I am using the librairy with an array of images where when you swipe left, an image is added at the beginning of the array, and when you swipe right, same but to the end of the array. It works wonderfully if i add an image to the end, but if i add an image at the beginning, the swiper skips one image (changes to the second image to the left instead of the first). I am guessing that the behavior comes from the fact that the onPageSelected of the librairy is fired to set the page to page = 0 (if my image is the 2nd one) even though i update the image array immediatly with an initialPage of 1. I will be trying to find a way to fix this or find a hack. If you have any cues, come forward!

**Comment by FabulouSebas** [comment]
I found a way around the bug with an option enforceInitialPage that flips to initialPage on update. The transition is smooth nonetheless. I could make a Pull Request if this fix seems legit.

**Comment by jonasmorthorst** [comment]
Hi @FabulouSebas. I'm also interested in adding images dynamically. Could you please tell how to achieve that? Thanks :)

**Comment by FabulouSebas** [comment]
Hi @jonasmorthorst ! It is quite simple to do! I am just adding a new image into my array of images that i have in my class's state when the user flips to the image that is the last or the first of the array. This way, there is always a picture to flip for the user. I am also modifying initialPage so it always points to the good picture.  I had an issue with react-native-image-gallery when adding dynamic image where on a swipe, sometimes it would skip a picture. I've made a PR on this. You might wanna make your own fork or start from my fork while the PR isnt approved: https://github.com/archriss/react-native-image-gallery/pull/75

**Comment by jonasmorthorst** [comment]
@FabulouSebas Thank you. It works, but I think it's a bit laggy, do you experience the same?
