### ISSUE TITLE
Error when image url is broken

### ISSUE THREAD

**Issue by djavier** [archriss/react-native-image-gallery#8]
I dont know if this is by design, and there si something additional i should be doing, but whenever i get a image url that doesn't work, for any external reason, i get the following error:

![image](https://user-images.githubusercontent.com/1663038/27594447-c7b792c8-5b27-11e7-9bad-3589060d8941.png)

I have omitted (scratch-out) the app name and hostname.

**Comment by Exilz** [comment]
Hi @djavier, it took quite some time for me to get back on the issues of this project, but it's finally fixed in the next version of the plugin. I'll publish it pretty soon.

Thanks for showing us this issue.
